### ISSUE TITLE
no compile

### ISSUE THREAD

**Issue by heiheshang** [lattenwald/erl-tdlib#2]
`Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]`
`Cargo 1.70.0 (ec8a8a0ca 2023-04-25)`
`./rebar3 compile
===> Verifying dependencies...
   Compiling tdlib-nif v0.2.0 (/home/oper/Programs/tracker_rpc/_build/default/lib/tdlib/crates/tdlib-nif)
error: could not compile `tdlib-nif` (lib) due to 2 previous errors; 18 warnings emitted
===> Uncaught error in rebar_core. Run with DIAGNOSTIC=1 to see stacktrace or consult rebar3.crashdump
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
`Error: {cargo_error,{101,
                     [#{<<"executable">> => null,
                        <<"features">> => [<<"default">>,<<"proc-macro">>],
                        <<"filenames">> =>
                            [<<"/home/oper/Programs/tracker_rpc/_build/default/lib/tdlib/target/debug/build/proc-macro2-0228cc05829635c7/build-script-build">>],
                        <<"fresh">> => true,
                        <<"manifest_path">> =>
                            <<"/home/oper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.36/Cargo.toml">>,
                        <<"package_id">> =>
                            <<"proc-macro2 1.0.36 (registry+https://github.com/rust-lang/crates.io-index)">>,
                        <<"profile">> =>
                            #{<<"debug_assertions">> => true,
                              <<"debuginfo">> => null,
                              <<"opt_level">> => <<"0">>,
                              <<"overflow_checks">> => true,
                              <<"test">> => false},
                        <<"reason">> => <<"compiler-artifact">>,
                        <<"target">> =>
                            #{<<"crate_types">> => [<<"bin">>],
                              <<"doc">> => false,<<"doctest">> => false,
                              <<"edition">> => <<"2018">>,
                              <<"kind">> => [<<"custom-build">>],
                              <<"name">> => <<"build-script-build">>,
                              <<"src_path">> =>
                                  <<"/home/oper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.36/build.rs">>,
                              <<"test">> => false}},
                      #{<<"cfgs">> =>
                            [<<"use_proc_macro">>,<<"wrap_proc_macro">>],
                        <<"env">> => [],<<"linked_libs">> => [],
                        <<"linked_paths">> => [],
                        <<"out_dir">> =>
                            <<"/home/oper/Programs/tracker_rpc/_build/default/lib/tdlib/target/debug/build/proc-macro2-6f335e9bd6f698be/out">>,
                        <<"package_id">> =>
                            <<"proc-macro2 1.0.36 (registry+https://github.com/rust-lang/crates.io-index)">>,
                        <<"reason">> => <<"build-script-executed">>},
                      #{<<"executable">> => null,
                        <<"features">> => [<<"default">>],
                        <<"filenames">> =>
                            [<<"/home/oper/Programs/tracker_rpc/_build/default/lib/tdlib/target/debug/deps/libunicode_xid-bfeb5d092a72ddea.rlib">>,
                             <<"/home/oper/Programs/tracker_rpc/_build/default/lib/tdlib/target/debug/deps/libunicode_xid-bfeb5d092a72ddea.rmeta">>],
                        <<"fresh">> => true,
                        <<"manifest_path">> =>
                            <<"/home/oper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unicode-xid-0.2.2/Cargo.toml">>,
                        <<"package_id">> =>
                            <<"unicode-xid 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)">>,
                        <<"profile">> =>
                            #{<<"debug_assertions">> => true,
                              <<"debuginfo">> => null,
                              <<"opt_level">> => <<"0">>,
                              <<"overflow_checks">> => true,
                              <<"test">> => false},
                        <<"reason">> => <<"compiler-artifact">>,
                        <<"target">> =>
                            #{<<"crate_types">> => [<<"lib">>],
                              <<"doc">> => true,<<"doctest">> => true,
                              <<"edition">> => <<"2015">>,
                              <<"kind">> => [<<"lib">>],
                              <<"name">> => <<"unicode-xid">>,
                              <<"src_path">> =>
                                  <<"/home/oper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/unicode-xid-0.2.2/src/lib.rs">>,
                              <<"test">> => true}},
                      #{<<"executable">> => null,
                        <<"features">> => [<<"default">>,<<"proc-macro">>],
                        <<"filenames">> =>
                            [<<"/home/oper/Programs/tracker_rpc/_build/default/lib/tdlib/target/debug/deps/libproc_macro2-1845b056c836bec2.rlib">>,
                             <<"/home/oper/Programs/tracker_rpc/_build/default/lib/tdlib/target/debug/deps/libproc_macro2-1845b056c836bec2.rmeta">>],
                        <<"fresh">> => true,
                        <<"manifest_path">> =>
                            <<"/home/oper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.36/Cargo.toml">>,
                        <<"package_id">> =>
                            <<"proc-macro2 1.0.36 (registry+https://github.com/rust-lang/crates.io-index)">>,
                        <<"profile">> =>
                            #{<<"debug_assertions">> => true,
                              <<"debuginfo">> => null,
                              <<"opt_level">> => <<"0">>,
                              <<"overflow_checks">> => true,
                              <<"test">> => false},
                        <<"reason">> => <<"compiler-artifact">>,
                        <<"target">> =>
                            #{<<"crate_types">> => [<<"lib">>],
                              <<"doc">> => true,<<"doctest">> => true,
                              <<"edition">> => <<"2018">>,
                              <<"kind">> => [<<"lib">>],
                              <<"name">> => <<"proc-macro2">>,
                              <<"src_path">> =>
                                  <<"/home/oper/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.36/src/lib.rs">>,
                              <<"test">> => true}},
                      #{<<"executable">> => null,
                        <<"features">> =>
                            [<<"clone-impls">>,<<"default">>,<<"derive">>,
                             <<"extra-traits">>,<<"full">>,<<"parsing">>,
                             <<"printing">>,<<"proc-macro">>,<<"quote">>],
                        <<"filenames">> =>         `

**Comment by lattenwald** [comment]
@heiheshang did you manage to fix compile problem? I didn't have a chance to have a look yet.

**Comment by heiheshang** [comment]
> @heiheshang did you manage to fix compile problem? I didn't have a chance to have a look yet.

I had to assemble tdjson by hand, it couldn’t be assembled without this library, and then I renamed the library from tdlib\priv\ crates\tdlib_nif\tdlib_nif.so to libtdlib_nif.so and put it in the priv directory.

**Comment by heiheshang** [comment]
This is what keeps popping up in the console, I don’t understand how it should be?
`tracker1@localhost)1> {ok, Pid} = tdlib:start_link().
{ok,<0.612.0>}
(tracker1@localhost)2> [ 3][t 0][1697445105.020716428][Client.cpp:280][&td_requests]	Begin to wait for updates with timeout 5.000000
                                                                                                                                       [ 3][t 4][1697445105.021602869][Td.cpp:2604][#1][!MultiTd]	Create Td with layer 165, database version 14 and version 48 on 4 threads
                                                                                                                                 [ 3][t 4][1697445105.022556066][Td.cpp:4101][#1][!Td][&td_requests]	Sending update: updateOption {
                                                                                        name = "version"
                                                                                                          value = optionValueString {
                                                                                                                                         value = "1.8.20"
            }
             }
              [ 3][t 4][1697445105.022625923][Td.cpp:4101][#1][!Td][&td_requests]	Sending update: updateOption {
                                                                                                                        name = "commit_hash"
                                                                                                                                              value = optionValueString {
                              value = "1c588eda01d0a68d18367522a6b0d58363c58565"
                                                                                  }
                                                                                   }
                                                                                    [ 3][t 4][1697445105.022635936][Td.cpp:4101][#1][!Td][&td_requests]	Sending update: updateAuthorizationState {
                                                            authorization_state = authorizationStateWaitTdlibParameters {
                                                                                                                           }
                                                                                                                            }
                                                                                                                             [ 3][t 0][1697445105.022647142][Client.cpp:293][&td_requests]	End to wait for updates, returning object 0 0x7f178c001c90
                                                                                                          [ 3][t 0][1697445105.032765865][Client.cpp:280][&td_requests]	Begin to wait for updates with timeout 5.000000
                                                                               [ 3][t 0][1697445105.032790899][Client.cpp:293][&td_requests]	End to wait for updates, returning object 0 0x7f178c001d00
`
