### ISSUE TITLE
some problem with paths and names

### ISSUE THREAD

**Issue by heiheshang** [lattenwald/erl-tdlib#3]
`===> Compiling tdlib
cp: не удалось выполнить stat для 'priv/crates/tdlib_nif/0.2.0/release/libtdlib_nif.so': Нет такого файла или каталога
===> Hook for compile failed!`
`ls priv/crates/tdlib_nif/
tdlib_nif.so`

**Comment by lattenwald** [comment]
@heiheshang Я так понимаю, ваш родной язык — русский?)

`rustler`, как я понял, ещё не поддерживает последние версии erlang. Я проверил с `erlang 25.3.2.1` (потому что он просто был под рукой) и с `rebar 3.22.0` (потому что `3.22.1` почему-то не хотел работать с этим эрлангом) — у меня собралось в чистом окружении без проблем. `libtdjson.so` у меня лежит в `/usr/local/lib/`.

Если у вас получится заставить всё заработать, то сообщите, пожалуйста, как это вышло.

**Comment by heiheshang** [comment]
У меня erlang 25.3.
Все собирается, только библиотека называется не так как в rebar.config прописанно
`{post_hooks, [{"(linux|darwin|solaris)", compile, "cp -f priv/crates/tdlib_nif/0.2.0/release/libtdlib_nif.so priv/"}]}.`

создается 
`priv/crates/tdlib_nif/ tdlib_nif.so`
я переименовываю руками и кладу в priv.
Пытаюсь отправить номер телефона, смс не приходит на телефон.

**Comment by heiheshang** [comment]
Все попытки установить конфиг заканчиваются вот этим
`Sending error for request 1: error { code = 400 message = "Valid api_id must be provided. Can be obtained at https://my.telegram.org" }`

**Comment by lattenwald** [comment]
@heiheshang

По порядку давайте

1. Пути. У вас Linux?
2. `api_id/api_hash` у вас с my.telegram.org?

И ещё одно, telegram теперь вроде разрешают регистрацию новых аккаунтов только через официальное приложение. После регистрации аккаунта аутентификация через клиенты на tdlib работает, если я правильно понимаю — код приходит в телеграм клиент, не SMS.

**Comment by heiheshang** [comment]
@lattenwald 
Разобрался , у вас потеган релиз без последних изменений, я брал тэг v0.3.8 а там setTdLibParametrs передает параметры массивом parametrs, в новой версии tdlib все передается одним потоком в мастере у вас изменения лежат, а в релизе нет.

**Comment by lattenwald** [comment]
А блин, я в продакшне использовал и тестил мастер а тег забыл. Спасибо, сейчас тег будет

**Comment by lattenwald** [comment]
v0.4.0

**Comment by heiheshang** [comment]
и почему-то  у меня rebar3_cargo плагин не включает при сборке в путь релиз,
`   Finished release [optimized] target(s) in 0.01s
===>   Copying libtdlib_nif to /home/oper/Programs/tracker_rpc/_build/default/lib/tdlib/priv/crates/tdlib_nif/tdlib_nif.so...`
и libtdlib_nif.so не делает

**Comment by lattenwald** [comment]
Я релизы с этим софтом не делал. Быстро не обещаю, как будет время посмотрю. Если разберётесь раньше — пулреквест вмержу с радостью)
